name: http2stream
version: 0.1.0
github: "MatrixAI/hs-http2stream"
license: Apache-2.0
author: ['Quoc-An Ho', 'CMCDragonkai']
maintainer: 'roger.qiu@matrix.ai'
copyright: '(c) 2017 Matrix AI'
description: Please see the README on Github at <https://github.com/MatrixAI/hs-http2stream#readme>

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Network.Stream.HTTP2
    - Network.Stream.HTTP2.Types
  other-modules:
    - Network.Stream.HTTP2.EncodeFrame
    - Network.Stream.HTTP2.Receiver
    - Network.Stream.HTTP2.Sender
  dependencies:
    - bytestring >= 0.10 && < 0.11
    - bytestring-strict-builder >= 0.4 && < 0.5
    - http-types >= 0.12 && < 0.13
    - http2 >= 1.6 && < 1.7
    - mtl >= 2.2 && < 2.3
    - stm >= 2.4 && < 2.5
    - containers >= 0.5 && < 0.6
    - extra >= 1.6 && < 1.7

tests:
  http2stream:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - http2stream
      - http2 >= 1.6 && < 1.7
      - network >= 2.6 && < 2.7


